from . import lightspeed_instance
from . import lightspeed_wizard
from . import product_feeds
from . import customer_feeds
from . import order_feeds
from . import res_partner
from . import product
from . import sale
from . import lightspeed_stock_wiz
from . import account
