# -*- coding: utf-8 -*-
{
    'name': "Base Marketplace",
    'version': '15.2.3.0.0',
    'summary': """Base Module for Marketplace""",
    'description': """Base Module for Marketplace""",
    'category': 'Extra Tools',
    'author': "Syncoria Inc.",
    'website': "https://www.syncoria.com",
    'company': 'Syncoria Inc.',
    'maintainer': 'Syncoria Inc.',
    'depends': ['base','stock','mail','sale'],
    'external_dependencies': {'python': []},
    'images': [
        'static/description/banner.png',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/res_config_settings.xml',
        'views/instance_view.xml',
        # 'views/sync_history.xml',
        'data/ir_sequence_data.xml',
        'wizard/update_stock.xml',
        # 'wizard/fetch_customers_wiz.xml',
        # 'data/ir_cron_data.xml',
    ],
    'price': 0,
    'currency': 'USD',
    'license': 'OPL-1',
    'support': "support@syncoria.com",
    'installable': True,
    'application': False,
    'auto_install': False,
    # 'uninstall_hook': 'uninstall_hook',
}